subprojects {
    apply plugin: 'java'

    group = 'io.github.benelog.spidersilk'
    version = '0.1.0'

    repositories {
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
