plugins {
    id 'java-library'
}

dependencies {
    api project(':spider-silk-core')

    api 'org.eclipse.jetty.websocket:jetty-websocket-jetty-server:12.1.12'

    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
